package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/swalha1999/lazycron/cron"
)

var pullCmd = &cobra.Command{
	Use:   "pull",
	Short: "Snapshot remote crontab as text stubs under .lazycron/_pulled/",
	Long: "Reads jobs from a crontab (local or remote) and writes one stub per job to " +
		".lazycron/_pulled/<id>.crontab. Stubs are read-only artefacts: agent .ts files " +
		"cannot be reconstructed from the crontab (the metadata-export parser is one-way), " +
		"so pull is for inspection and recovery, not round-tripping.",
	RunE: runPull,
}

var (
	pullServer  string
	pullProject string
	pullDir     string
)

func init() {
	pullCmd.Flags().StringVarP(&pullServer, "server", "s", "", "target server name from config")
	pullCmd.Flags().StringVarP(&pullProject, "project", "p", "", "only pull jobs from this project group")
	pullCmd.Flags().StringVar(&pullDir, "dir", "", "path to .lazycron directory (default: ./.lazycron)")
	rootCmd.AddCommand(pullCmd)
}

func runPull(cmd *cobra.Command, args []string) error {
	b, err := resolveBackend(pullServer)
	if err != nil {
		return err
	}
	defer b.Close()

	jobs, err := b.ReadJobs()
	if err != nil {
		return fmt.Errorf("failed to read jobs: %w", err)
	}

	if pullProject != "" {
		jobs = filterByProject(jobs, pullProject)
	}

	if len(jobs) == 0 {
		fmt.Println("No jobs found to pull")
		return nil
	}

	for i := range jobs {
		if jobs[i].ID == "" {
			jobs[i].ID = cron.GenerateID()
		}
	}

	dir := pullDir
	if dir == "" {
		dir = ".lazycron"
	}
	stubDir := filepath.Join(dir, "_pulled")
	if err := os.MkdirAll(stubDir, 0o755); err != nil {
		return fmt.Errorf("create directory %s: %w", stubDir, err)
	}

	for _, j := range jobs {
		if err := writeJobStub(stubDir, j); err != nil {
			return err
		}
	}

	fmt.Printf("Pulled: %d jobs written to %s\n", len(jobs), stubDir)
	return nil
}

func filterByProject(jobs []cron.Job, project string) []cron.Job {
	var filtered []cron.Job
	for _, j := range jobs {
		if j.Project == project {
			filtered = append(filtered, j)
		}
	}
	return filtered
}

// writeJobStub writes a human-readable snapshot of a single job. The stub is
// not consumed by sync — sync reads .sandcastle/jobs/*.ts. The stub strips the
// `cd <project-dir> && ` prefix that sync injects so the user sees the
// authored command, not the wrapped one.
func writeJobStub(dir string, j cron.Job) error {
	cmdText, projectPath := cron.StripProjectCd(j.Command)

	content := "# Auto-generated by lazycron pull — read-only snapshot.\n"
	content += "# Sandcastle .ts files cannot be reconstructed; this stub is for inspection.\n"
	content += fmt.Sprintf("# id: %s\n", j.ID)
	content += fmt.Sprintf("# name: %s\n", j.Name)
	content += fmt.Sprintf("# schedule: %s\n", j.Schedule)
	if j.Project != "" {
		content += fmt.Sprintf("# project: %s\n", j.Project)
	}
	if projectPath != "" {
		content += fmt.Sprintf("# project_dir: %s\n", projectPath)
	}
	if j.Tag != "" {
		content += fmt.Sprintf("# tag: %s\n", j.Tag)
	}
	if j.TagColor != "" {
		content += fmt.Sprintf("# tag_color: %s\n", j.TagColor)
	}
	if !j.Enabled {
		content += "# enabled: false\n"
	}
	if j.OneShot {
		content += "# once: true\n"
	}
	content += "\n"
	content += cmdText + "\n"

	path := filepath.Join(dir, j.ID+".crontab")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
