package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/swalha1999/lazycron/cron"
	"gopkg.in/yaml.v3"
)

func TestFilterByProject(t *testing.T) {
	jobs := []cron.Job{
		{ID: "a", Project: "backend"},
		{ID: "b", Project: "frontend"},
		{ID: "c", Project: "backend"},
		{ID: "d", Project: ""},
	}

	filtered := filterByProject(jobs, "backend")
	if len(filtered) != 2 {
		t.Fatalf("expected 2 jobs, got %d", len(filtered))
	}
	for _, j := range filtered {
		if j.Project != "backend" {
			t.Errorf("unexpected project %q", j.Project)
		}
	}
}

func TestFilterByProject_CaseSensitive(t *testing.T) {
	jobs := []cron.Job{
		{ID: "a", Project: "Backend"},
		{ID: "b", Project: "backend"},
	}

	filtered := filterByProject(jobs, "backend")
	if len(filtered) != 1 {
		t.Fatalf("expected 1 job (case-sensitive), got %d", len(filtered))
	}
	if filtered[0].ID != "b" {
		t.Errorf("wrong job filtered: %q", filtered[0].ID)
	}
}

func TestFilterByProject_NoMatch(t *testing.T) {
	jobs := []cron.Job{
		{ID: "a", Project: "backend"},
	}

	filtered := filterByProject(jobs, "nonexistent")
	if len(filtered) != 0 {
		t.Fatalf("expected 0 jobs, got %d", len(filtered))
	}
}

func TestWriteJobYAML_BasicJob(t *testing.T) {
	dir := t.TempDir()
	job := cron.Job{
		ID:       "db-backup",
		Name:     "Database Backup",
		Schedule: "0 3 * * *",
		Command:  "pg_dump mydb",
		Enabled:  true,
		Project:  "backend",
		Tag:      "DB",
		TagColor: "#a6e3a1",
	}

	if err := writeJobYAML(dir, job); err != nil {
		t.Fatalf("writeJobYAML: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "db-backup.yaml"))
	if err != nil {
		t.Fatalf("read file: %v", err)
	}

	content := string(data)
	if !strings.HasPrefix(content, "# Auto-generated by lazycron pull\n") {
		t.Error("missing header comment")
	}

	// Parse back and verify fields.
	var jf jobFile
	if err := yaml.Unmarshal(data, &jf); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if jf.Name != "Database Backup" {
		t.Errorf("name = %q", jf.Name)
	}
	if jf.Schedule != "0 3 * * *" {
		t.Errorf("schedule = %q", jf.Schedule)
	}
	if jf.Command != "pg_dump mydb" {
		t.Errorf("command = %q", jf.Command)
	}
	if jf.Project != "backend" {
		t.Errorf("project = %q", jf.Project)
	}
	if jf.Tag != "DB" {
		t.Errorf("tag = %q", jf.Tag)
	}
	if jf.TagColor != "#a6e3a1" {
		t.Errorf("tag_color = %q", jf.TagColor)
	}
	if jf.Enabled != nil {
		t.Error("enabled should be omitted for enabled jobs")
	}
	if jf.Once {
		t.Error("once should be false")
	}
}

func TestWriteJobYAML_DisabledJob(t *testing.T) {
	dir := t.TempDir()
	job := cron.Job{
		ID:       "disabled-job",
		Name:     "Disabled",
		Schedule: "* * * * *",
		Command:  "echo off",
		Enabled:  false,
	}

	if err := writeJobYAML(dir, job); err != nil {
		t.Fatalf("writeJobYAML: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "disabled-job.yaml"))
	if err != nil {
		t.Fatalf("read file: %v", err)
	}

	var jf jobFile
	if err := yaml.Unmarshal(data, &jf); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if jf.Enabled == nil || *jf.Enabled != false {
		t.Error("expected enabled=false")
	}
}

func TestWriteJobYAML_OneShotJob(t *testing.T) {
	dir := t.TempDir()
	job := cron.Job{
		ID:      "once-job",
		Name:    "Run Once",
		Schedule: "0 0 * * *",
		Command: "echo once",
		Enabled: true,
		OneShot: true,
	}

	if err := writeJobYAML(dir, job); err != nil {
		t.Fatalf("writeJobYAML: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "once-job.yaml"))
	if err != nil {
		t.Fatalf("read file: %v", err)
	}

	var jf jobFile
	if err := yaml.Unmarshal(data, &jf); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if !jf.Once {
		t.Error("expected once=true")
	}
}

func TestWriteJobYAML_OmitsDefaultFields(t *testing.T) {
	dir := t.TempDir()
	job := cron.Job{
		ID:       "minimal",
		Name:     "Minimal",
		Schedule: "* * * * *",
		Command:  "echo hi",
		Enabled:  true,
	}

	if err := writeJobYAML(dir, job); err != nil {
		t.Fatalf("writeJobYAML: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "minimal.yaml"))
	if err != nil {
		t.Fatalf("read file: %v", err)
	}

	content := string(data)
	if strings.Contains(content, "project:") {
		t.Error("should not include empty project")
	}
	if strings.Contains(content, "tag:") {
		t.Error("should not include empty tag")
	}
	if strings.Contains(content, "tag_color:") {
		t.Error("should not include empty tag_color")
	}
	if strings.Contains(content, "enabled:") {
		t.Error("should not include enabled when true")
	}
	if strings.Contains(content, "once:") {
		t.Error("should not include once when false")
	}
}

func TestWriteJobYAML_OverwritesExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "overwrite-me.yaml")

	if err := os.WriteFile(path, []byte("old content"), 0o644); err != nil {
		t.Fatal(err)
	}

	job := cron.Job{
		ID:       "overwrite-me",
		Name:     "New Content",
		Schedule: "* * * * *",
		Command:  "echo new",
		Enabled:  true,
	}

	if err := writeJobYAML(dir, job); err != nil {
		t.Fatalf("writeJobYAML: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	if strings.Contains(string(data), "old content") {
		t.Error("file should have been overwritten")
	}

	var jf jobFile
	if err := yaml.Unmarshal(data, &jf); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if jf.Name != "New Content" {
		t.Errorf("name = %q, want New Content", jf.Name)
	}
}

// Verify round-trip: write YAML then read it back as a valid job file.
func TestWriteJobYAML_RoundTrip(t *testing.T) {
	dir := t.TempDir()
	original := cron.Job{
		ID:       "round-trip",
		Name:     "Round Trip",
		Schedule: "0 3 * * *",
		Command:  "pg_dump mydb | gzip > backup.sql.gz",
		Enabled:  true,
		Project:  "backend",
		Tag:      "DB",
		TagColor: "#a6e3a1",
	}

	if err := writeJobYAML(dir, original); err != nil {
		t.Fatalf("writeJobYAML: %v", err)
	}

	// Read back using the sync command's readJobFiles.
	jobs, err := readJobFiles(dir)
	if err != nil {
		t.Fatalf("readJobFiles: %v", err)
	}
	if len(jobs) != 1 {
		t.Fatalf("expected 1 job, got %d", len(jobs))
	}

	got := jobs[0]
	if got.ID != "round-trip" {
		t.Errorf("ID = %q", got.ID)
	}
	if got.Name != "Round Trip" {
		t.Errorf("Name = %q", got.Name)
	}
	if got.Schedule != "0 3 * * *" {
		t.Errorf("Schedule = %q", got.Schedule)
	}
	if got.Command != "pg_dump mydb | gzip > backup.sql.gz" {
		t.Errorf("Command = %q", got.Command)
	}
	if got.Project != "backend" {
		t.Errorf("Project = %q", got.Project)
	}
	if got.Tag != "DB" {
		t.Errorf("Tag = %q", got.Tag)
	}
	if got.TagColor != "#a6e3a1" {
		t.Errorf("TagColor = %q", got.TagColor)
	}
}
