package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/swalha1999/lazycron/cron"
	"gopkg.in/yaml.v3"
)

var pullCmd = &cobra.Command{
	Use:   "pull",
	Short: "Download remote jobs as YAML files",
	Long:  "Reads jobs from a crontab (local or remote) and writes them as .lazycron/jobs/*.yaml files. This is the inverse of lazycron sync.",
	RunE:  runPull,
}

var (
	pullServer  string
	pullProject string
	pullDir     string
)

func init() {
	pullCmd.Flags().StringVarP(&pullServer, "server", "s", "", "target server name from config")
	pullCmd.Flags().StringVarP(&pullProject, "project", "p", "", "only pull jobs from this project group")
	pullCmd.Flags().StringVar(&pullDir, "dir", "", "path to .lazycron directory (default: ./.lazycron)")
	rootCmd.AddCommand(pullCmd)
}

func runPull(cmd *cobra.Command, args []string) error {
	b, err := resolveBackend(pullServer)
	if err != nil {
		return err
	}
	defer b.Close()

	jobs, err := b.ReadJobs()
	if err != nil {
		return fmt.Errorf("failed to read jobs: %w", err)
	}

	if pullProject != "" {
		jobs = filterByProject(jobs, pullProject)
	}

	if len(jobs) == 0 {
		fmt.Println("No jobs found to pull")
		return nil
	}

	// Ensure all jobs have an ID.
	for i := range jobs {
		if jobs[i].ID == "" {
			jobs[i].ID = cron.GenerateID()
		}
	}

	dir := pullDir
	if dir == "" {
		dir = ".lazycron"
	}
	jobsDir := filepath.Join(dir, "jobs")

	if err := os.MkdirAll(jobsDir, 0o755); err != nil {
		return fmt.Errorf("create directory %s: %w", jobsDir, err)
	}

	for _, j := range jobs {
		if err := writeJobYAML(jobsDir, j); err != nil {
			return err
		}
	}

	fmt.Printf("Pulled: %d jobs written to %s\n", len(jobs), jobsDir)
	return nil
}

func filterByProject(jobs []cron.Job, project string) []cron.Job {
	var filtered []cron.Job
	for _, j := range jobs {
		if j.Project == project {
			filtered = append(filtered, j)
		}
	}
	return filtered
}

func writeJobYAML(dir string, j cron.Job) error {
	jf := jobFile{
		Name:     j.Name,
		Schedule: j.Schedule,
		Command:  j.Command,
	}

	if j.Project != "" {
		jf.Project = j.Project
	}
	if j.Tag != "" {
		jf.Tag = j.Tag
	}
	if j.TagColor != "" {
		jf.TagColor = j.TagColor
	}
	if !j.Enabled {
		enabled := false
		jf.Enabled = &enabled
	}
	if j.OneShot {
		jf.Once = true
	}

	data, err := yaml.Marshal(jf)
	if err != nil {
		return fmt.Errorf("marshal job %s: %w", j.ID, err)
	}

	header := "# Auto-generated by lazycron pull\n"
	content := header + string(data)

	path := filepath.Join(dir, j.ID+".yaml")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	return nil
}

